CREATE TABLE IF NOT EXISTS M_USER (
	 USER_ID INT NOT NULL AUTO_INCREMENT
	,USER_NM VARCHAR(100) NOT NULL
	,PASSWORD VARCHAR(10) NOT NULL
	,REGIST_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP 
	,PRIMARY KEY(USER_ID)
);
CREATE TABLE IF NOT EXISTS T_CHAT_LOG (
	 CHAT_GROUP_ID INT NOT NULL
	,CHAT_DATE TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,USER_ID INT NOT NULL
	,COMMENT VARCHAR(200) NOT NULL
	,DELETE_FLG CHAR(1) NOT NULL DEFAULT '0'
	,TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY(CHAT_GROUP_ID, CHAT_DATE)
);
CREATE TABLE IF NOT EXISTS T_FREND (
	 USER_ID INT NOT NULL
	,FREND_USER_ID INT NOT NULL
	,REGIST_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,DELETE_FLG CHAR(1) NOT NULL DEFAULT '0'
	,TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (USER_ID, FREND_USER_ID)
);
CREATE TABLE IF NOT EXISTS T_CHAT_GROUP (
	 CHAT_GROUP_ID INT NOT NULL AUTO_INCREMENT
	,USER_ID INT NOT NULL
	,REGIST_DATE DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
	,DELETE_FLG CHAR(1) NOT NULL DEFAULT '0'
	,TIME_STAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
	,PRIMARY KEY (CHAT_GROUP_ID, USER_ID)
);
